### PR TITLE
Implementation of caching with Mongo GridFS

### PR DESCRIPTION
**Pull request by ColinFay**
This PR implements caching with MongoDB

``` r
library(memoise)
packageVersion("memoise")
#> [1] '1.1.0.9001'

# Setting a gridFS connection
mongo_grid <- mongolite::gridfs(
  db = "memoize",
  prefix = "memoize"
)

# Creating a cache object and function
mong <- cache_mongo(mongo_grid)
mem_runif <- memoise(runif, cache = mong)

# Try
mem_runif(2)
#> [1] 0.2303921 0.6463652
mem_runif(2)
#> [1] 0.2303921 0.6463652
forget(mem_runif)
#> [1] TRUE
mem_runif(2)
#> [1] 0.4622024 0.9150384
mem_runif(2)
#> [1] 0.4622024 0.9150384
mem_runif(2)
#> [1] 0.4622024 0.9150384

# Remove the cache
mong$reset()
#> [1] TRUE
mem_runif(2)
#> [1] 0.6719828 0.7780810
mem_runif(2)
#> [1] 0.6719828 0.7780810

# Adding some keys
mem_runif(3)
#> [1] 0.2543146 0.9049935 0.2460525
mem_runif(4)
#> [1] 0.6758450 0.5329271 0.8253259 0.9457335
mem_runif(5)
#> [1] 0.4468803 0.6330407 0.7605470 0.9637121 0.2600788

# List the keys
mong$keys()
#> [1] "e975ae617f1a88c58c94c1b21f1528d3eabf53b45cd81575b630bcd682b8b45fc214e67403e8f7e897a70003bd934659501ff4ff67cc8aaf3a80fe8cba551499"
#> [2] "2028fc4c0ccf0dfed6990ca22775ef8d3d12f91738dfc131cd7684e929f27a9093eb3ddfbfc2313a33a932f897546564a432709a341c0543fa54083e273a0c1d"
#> [3] "ee8a3b2f72a7a3dfd3bdbc21dbeb14167e7418022844ff99ead672e249baefb44584a58229675989d2746799c0b784b54750548eb16ac635b556b1cae0707bb2"
#> [4] "03645ed90db5873fbc1ef02ee837b2dc5e31cc3407ce30285a75f82bd55078ca946af74ffc5c92480c5a33a22b9ee3e88f2dbb657decbae70cd30cffbd8d3a81"

# Drop one
one <- mong$keys()[1]
two <- mong$keys()[2]
mong$drop_key(one)
#>                         id
#> 1 5e9ec0a380f47e31d91aadc4
#>                                                                                                                               name
#> 1 e975ae617f1a88c58c94c1b21f1528d3eabf53b45cd81575b630bcd682b8b45fc214e67403e8f7e897a70003bd934659501ff4ff67cc8aaf3a80fe8cba551499
#>   size                date type
#> 1  128 2020-04-21 11:45:07 <NA>
#>                                                                                                                                         metadata
#> 1 { "key" : "e975ae617f1a88c58c94c1b21f1528d3eabf53b45cd81575b630bcd682b8b45fc214e67403e8f7e897a70003bd934659501ff4ff67cc8aaf3a80fe8cba551499" }
mong$keys()
#> [1] "2028fc4c0ccf0dfed6990ca22775ef8d3d12f91738dfc131cd7684e929f27a9093eb3ddfbfc2313a33a932f897546564a432709a341c0543fa54083e273a0c1d"
#> [2] "ee8a3b2f72a7a3dfd3bdbc21dbeb14167e7418022844ff99ead672e249baefb44584a58229675989d2746799c0b784b54750548eb16ac635b556b1cae0707bb2"
#> [3] "03645ed90db5873fbc1ef02ee837b2dc5e31cc3407ce30285a75f82bd55078ca946af74ffc5c92480c5a33a22b9ee3e88f2dbb657decbae70cd30cffbd8d3a81"

# Test if has key
mong$has_key(one)
#> [1] FALSE
mong$has_key(two)
#> [1] TRUE
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by ColinFay** [comment]
Hey All! 

Just passing by to see if this PR is of interest to you (otherwise I'll close it and share it in an external package). 

Let me know! 

Colin

**Comment by jimhester** [comment]
Hey Colin, thanks for the PR! I am now generally thinking these types of backends are better done in external packages, so I think that is the best option.

**Comment by jimhester** [comment]
I would be happy to link to your package from the memoise readme and documentation if you would like however!

**Comment by ColinFay** [comment]
@jimhester Thanks! I closed this PR because I'm indeed switching this to a standalone package :) 

I'll send a PR for linking in the README when it's ready, thank you!

**Comment by wch** [comment]
Just a heads up: I added a bit of information to the README about how the new-style caching objects allow memoise to avoid potential race conditions. You should be able to modify your code to also avoid races.
https://github.com/r-lib/memoise/commit/e9dc99ce37b620a40d7d5916a298fdba1677049a

**Comment by ColinFay** [comment]
@wch thanks for the heads up! 

If I understand things correctly, I'll potentially be in a case where the key is removed from the cache _after_ `has_key()` has returned `TRUE`, then we try to read the value it fails, so I need to manage this potential case?

**Comment by wch** [comment]
Right, if you do something like this, you could have a problem because the object disappears between the `has_key()` and `get()`:

```R
if (cache$has_key(key)) {
  x <- cache$get(key)
}
```

Memoise now does something like this pseudocode:

```R
x <- cache$get(key)

if (is.key_missing(x)) {
  # Do something
} else {
  # Do something else
}
```

So there is no longer a race condition in memoise. But it is possible for the caching object itself to have a race condition internally. For both `cache_mem` and `cache_disk`, the `get()` method is implemented in a way that avoids race conditions.

If you provide an old-style cache to `memoise()`, it will automatically wrap it using `wrap_old_cache()`, but that (necessarily) is implemented with the problematic method that could have a race:

https://github.com/r-lib/memoise/blob/e9dc99ce37b620a40d7d5916a298fdba1677049a/R/old_cache.R#L14-L19

**Pull request closed without merging**
