### PR TITLE
Add faster alternative to save/readRDS

### PR DESCRIPTION
**Pull request by rhjp**
The qs package is much faster at serialising R objects to file, therefore adding as an optional addition, selectable via the `compress` argument.

- [x] Create `cache_set_fs` and `cache_get_fs` to be shared by `cache_filesystem`, `cache_gcs` and `cache_s3`
- [x] Added tests for all compression options (including these new ones)
- [X] Update documentation

### CODE REVIEW

**Comment by jimhester** [comment]
I think it would be better to make `qs` an optional dependency by putting `qs` in Suggests rather than Imports. You will also have to use something like `requireNamespace()` and throw an error if someone tries to use qs compression and the package is not installed.

**Comment by rhjp** [comment]
@jimhester, `qs` is now an optional dependency. I have added the `requireNamespace()` in the same was as the gcs and s3 cache does in this package. Also, to make things a bit more interesting, I've also added the option to have a compressed in-memory cache (again via `qs`). Similarly substantial space savings are achieved, but this time in memory. It is slower than the default in-memory cache though.

**Comment by rhjp** [comment]
@jimhester, ready for re-review now

**Comment by jefferis** [comment]
Just a note that I also needed something like this and would be happy to see this PR integrated. I ended up hand coding with brotli compression (brotli quality=2 is >5x faster than gzip and compresses better for my data) before I noticed the qs package. Compressing in memory was actually very important for me, so I would second that as a useful addition. I would add that qs_high can have useful additional compression over qs_balanced with rather little impact on compression speed in my hands, so could be worth adding this as an option.

**Comment by rhjp** [comment]
The actual caching in this package is now performed by [cachem](https://github.com/r-lib/cachem), so I'll close this PR. [cachem](https://github.com/r-lib/cachem) still has RDS as the only option for saving to disk, therefore this PR could still be relevant, just not in the right place.

**Pull request closed without merging**
