### PR TITLE
Add fixed size cache

### PR DESCRIPTION
**Pull request by mbertolacci**
This adds a new cache, `cache_fixed_size`, which wraps another cache (by default `cache_memory`), and which drops a key/value pair when the size limit is exceeded. I think this is useful in long running programs such as shiny apps where you want to limit memory usage.

By default the cache evicts keys according to a first-in, first-out (FIFO) strategy, with a least-recently-used (LRU) eviction strategy also available. Eviction strategies follow an API so a user could implement their own. (It's not here, but I guess one could make a similar cache that has a maximum memory size rather than a maximum number of items. In that case the same eviction strategies could be used.)

Happy to mess with the nomenclature if desired, for instance by calling an eviction strategy a [cache replacement policy](https://en.wikipedia.org/wiki/Cache_replacement_policies) instead.

Is this fixed size cache of interest as an addition to this package? This could alternatively be moved to an extensions package if it's considered too niche. My personal view is that limiting the cache size is good programming practice to avoid memory leaks, so I think it's a good candidate for this package.

### CODE REVIEW

**Comment by mbertolacci** [comment]
Bump. I should add that this addresses #53.

**Comment by mbertolacci** [comment]
Just a note that I brought this up to date with recent changes to the package, and it passes all tests.

**Comment by wch** [comment]
Hi, this functionality was actually added in the recent release of memoise, version 2.0.0, by using caching objects from the cachem package. See https://github.com/r-lib/memoise#caches for more information.

**Comment by mbertolacci** [comment]
Ah! Apologies, I didn't realise that. Very good then :)

**Pull request closed without merging**
