### PR TITLE
ignore specified arguments when hashing

### PR DESCRIPTION
**Pull request by coolbutuseless**
This PR addresses https://github.com/r-lib/memoise/issues/74

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks, mostly it looks fine, but I am not sure about the argument name, maybe `omit_args()` or `args_omit()` would be better?

**Comment by coolbutuseless** [comment]
Not attached to current naming.  I like "omit_args()"

**Comment by jimhester** [comment]
Ok, could you update this to use `omit_args()` and then I can merge it

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
